### ISSUE TITLE
GET /question/all/{userId} -> null pointer exception

### ISSUE THREAD

**Issue by devatearth** [devatearth/Quora_a_socialApp#29]
![Capture](https://user-images.githubusercontent.com/64774809/101237519-76a4bc00-36ff-11eb-8ad4-8b482ba8e1c1.PNG)

When trying to get all the questions posted by a user. facing null pointer exception.

**Comment by navvenraj** [comment]
Getting null value while trying to get getLogoutAt() from user authentity

**Comment by devatearth** [comment]
Fixed it. The issue was the validation for null scenario is not added.
