### ISSUE TITLE
PUT /question/edit/{questionId} - null pointer exception

### ISSUE THREAD

**Issue by devatearth** [devatearth/Quora_a_socialApp#30]
![image](https://user-images.githubusercontent.com/64774809/101237546-b23f8600-36ff-11eb-9b2a-21df2f17452a.png)

When trying to edit a question getting null pointer exception.

**Comment by navvenraj** [comment]
Getting null value while trying to get getLogoutAt() from user authentity

**Comment by devatearth** [comment]
Fixed it. The issue was the validation for null scenario is not added.
