### ISSUE TITLE
DELETE /question/delete/{questionId} - null pointer exception

### ISSUE THREAD

**Issue by devatearth** [devatearth/Quora_a_socialApp#31]
![image](https://user-images.githubusercontent.com/64774809/101237558-e024ca80-36ff-11eb-94ee-0a6752628f19.png)

When trying to delete a question getting null pointer exception.

**Comment by navvenraj** [comment]
Getting null value while trying to get  getLogoutAt()  from user authentity

**Comment by devatearth** [comment]
Fixed it. The issue was the validation for null scenario is not added.
