### ISSUE TITLE
Test - Endpoint's -1

### ISSUE THREAD

**Issue by devatearth** [devatearth/Quora_a_socialApp#32]
![image](https://user-images.githubusercontent.com/64774809/101237822-d603cb80-3701-11eb-932b-1a282773585c.png)

**Comment by devatearth** [comment]
Completed Testing user-controller.
![image](https://user-images.githubusercontent.com/64774809/101238722-0e0e0d00-3708-11eb-9723-c56887b6c1ad.png)

All test passed.

**Comment by navvenraj** [comment]
Checked the Common Controller all test cases passed.
Scenarios tested -> 
1. By passing the correct requirements. 
2. Passing the invalid user Id. 
3. Passing the invalid access token.
